{block content}


{include '../default-top.latte' 
	breadcrumb=>array( array('name'=>_('Spravovanie objednávky')) ), 
	name=>_('Spravovanie objednávky')
}


<div class="content">


{control msg _('Vaša objednávka bola úspešne spracovaná.'),_('Potvrdenie o objednávke Vám bolo zaslané na e-mailovú adresu. Ďakujeme Vám za nákup!')}


<!-- Google Code for n&aacute;kup a predaj Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 965112664;
var google_conversion_language = "sk";
var google_conversion_format = "2";
var google_conversion_color = "cccccc";
var google_conversion_label = "DTVOCKiWpAMQ2OaZzAM";
var google_conversion_value = 0;
if (150) {
 google_conversion_value = 150;
}
/* ]]> */
</script>
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/965112664/?value=150&amp;label=DTVOCKiWpAMQ2OaZzAM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
</div>