
{if $paginator->pageCount > 1}
<div class="c-paginator">
 <div class="paginator">
	 
	 {if $paginator->isFirst()}
		<span class="paginator-first-inactive"><a href="{link this, 'page' => $paginator->page}"><img src="/images/paginator-first-inactive.png" />&nbsp;Predchádzajúca stránka</a></span>
	{else}
		<span class="paginator-first-active"><a href="{link this, 'page' => $paginator->page - 1}"><img src="/images/paginator-first-active.png" />&nbsp;Predchádzajúca stránka</a></span>
	{/if}

		
	{foreach $steps as $step}
		{if $step == $paginator->page}
			<span class="current">{$step}</span>
		{else}
			<a href="{link this, 'page' => $step}">{$step}</a>
		{/if}
		{if $iterator->nextValue > $step + 1}<span>…</span>{/if}
	{/foreach}
		
		
	{if $paginator->isLast()}
		<span class="paginator-last-inactive"><a href="{link this, 'page' => $paginator->page}">Nasledujúca stránka&nbsp;<img src="/images/paginator-last-active.png" /></a></span>
		{else}
		<span class="paginator-last-active"><a href="{link this, 'page' => $paginator->page + 1}">Nasledujúca stránka&nbsp;<img src="/images/paginator-last-active.png" /></a></span>
	{/if}	
 </div>

</div><!-- c paginator -->
{/if}