<div class="commentsHolder">
	
	<a href="#" id="addComment">Pridať komentár ></a>
	
	
	<div id="addCommentHolder">
		{control commentForm}
		<script type="text/javascript">
			$('#addCommentHolder').hide();
			$('#addComment').click(function(e) {
				e.preventDefault();	
			  $('#addCommentHolder').slideToggle('slow', function() {
			    // Animation complete.
			  });
			});
	
		</script>
	</div>
	
{assign parent => NULL}


{block #comments}
<div n:if="$comments" class="commentBlock">
{foreach $comments[$parent] as $comment}
	
	
	<div class="commentItem {if $iterator->isLast()}last{/if} commentPage{if !($presenter->commentCounter % 10) }{?$presenter->commentPage++}{/if}{$presenter->commentPage}">
	{? $presenter->commentCounter++}
		<div class="nameDateHolder">
			<span class="name">{$comment['name']}</span> 
			<span class="date">{$comment['adddate']|date:"d.m.Y H:i:s"}</span>
			 
		</div>
		<div class="commentText">
			<div class="quoteLeft"></div>
			<div class="quoteRight"></div>
			{$comment['text']}
			
			<div class="answer"><a href="#{$comment['id_comment']}" class="linkAnswer" rel="{$comment['id_node']}|{$comment['id_comment']}" title="Odpovedať">Odpovedať</a></div>
		</div>
	</div>
	{ifset $comments[$comment->id_comment]}
		{include #this parent => $comment->id_comment}
	{/if}
{/foreach}
</div>
{/block}

{if $presenter->commentPage>1}
<div>
	<div style="color: silver; font-size:11px;padding-top:10px;">Stránkovanie komentárov</div>
	<div class="paginator">
	{for $i=1; $i<=$presenter->commentPage; ++$i}
		<a href="#" class="commentPaging" rel="{$i}">{$i}</a>
	{/for}
	</div>
</div>
{/if}



</div>

<div id="CommentAnswerForm">
	<a href="#" id="CommentAnswerFormClose" style="float:right; ">Zavrieť</a>
	<h3 style="padding-bottom: 5px;">Odpoveď</h3>
	{control commentAnswerForm}
</div>

<script type="text/javascript">
	jQuery.fn.center = function (absolute) {
	    return this.each(function () {
	        var t = jQuery(this);
	
	        t.css({
	            position:    absolute ? 'absolute' : 'fixed', 
	            left:        '50%', 
	            top:        '50%', 
	            zIndex:        '99'
	        }).css({
	            marginLeft:    '-' + (t.outerWidth() / 2) + 'px', 
	            marginTop:    '-' + (t.outerHeight() / 2) + 'px'
	        });
	
	        if (absolute) {
	            t.css({
	                marginTop:    parseInt(t.css('marginTop'), 10) + jQuery(window).scrollTop(), 
	                marginLeft:    parseInt(t.css('marginLeft'), 10) + jQuery(window).scrollLeft()
	            });
	        }
	    });
	};
	$("#CommentAnswerForm").hide();
	$('a.linkAnswer').click( function(e){
		e.preventDefault();
		var el = $(this);
		var pom = el.attr('rel').split("|");
		var id_node = pom[0];
		var parent_comment = pom[1];

		$('#frmcommentAnswerForm-id_node').attr('value', id_node );
		$('#frmcommentAnswerForm-comment_parent').attr('value', parent_comment );
		
		$("#CommentAnswerForm").center();
					
		
		$("#CommentAnswerForm").show();	
	});

	$('#CommentAnswerFormClose').click(function(e){
		e.preventDefault();
		$("#CommentAnswerForm").hide();
	})	
{*<!--
window.addEvent('domready', function() {




	$$('a.linkAnswer').addEvent('click', function(e){
		e.stop(); 

		var el = this;
		var pom = el.get('rel').split("|");
		var id_node = pom[0];
		var parent_comment = pom[1];
	
		$('frmcommentAnswerForm-id_node').set('value', id_node );
		$('frmcommentAnswerForm-comment_parent').set('value', parent_comment );
		
		$("CommentAnswerForm").setStyle('display', 'block');
		
		$("CommentAnswerForm").fade(1);
		$("CommentAnswerForm").position( { position: 'center' });
	})
	
	$('CommentAnswerFormClose').addEvent('click', function(e){
		e.stop();
		$("CommentAnswerForm").fade(0);
	})	

	$("CommentAnswerForm").fade(0);





});
//-->
*}
</script>
