<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Stránka je vo výstavbe | Page is under construction.</title>
<link rel="stylesheet" media="screen,projection,tv" href="http://www.vizion.sk/css/error_screen.css" type="text/css" />


</head>

<body>

<div id="content">

<h1>Stránka je vo výstavbe</h1>
<h5> Page is under construction</h5>

</div>


</body>
</html>
