<ul id="ImageList{$id}">
		{foreach $list as $l}
		  <li id="item_id_image_{$l['id_file']}">
		    <form class="imageForm" action="" method="post">
		      <div class="image">
					<a href="{? echo Files::getFileURL($l['src'],$l['ext'])}" target="_blank">
						{if $l['ext'] == 'jpg' OR $l['ext'] == 'gif' OR $l['ext'] == 'png'}
						  <img src="{? echo Files::gURL($l['src'],$l['ext'],50,40,5)}" alt="" />
						 {else}
						 <img src="/images-system/attachment/icon_{$l['ext']}.jpg" alt="{$l['ext']}" />

						{/if}
					</a>
		      </div>
		      <div class="holder">
			Popis:
			<input style="width:200px;" type="text" name="alt" value="{$l['alt']}"/>
			<input type="hidden" name="id_file" value="{$l['id_file']}">
			<input class="saveDescriptionButton" type="submit" name="saveDescription" value="Ulož popis" />
			<span><img src="/templates/global_img/up.gif" alt="" /><img src="/templates/global_img/down.gif" alt="" /></span>
			<a href="javascript:confl('Naozaj chcete odstrániť obrázok?','{$parsed_url['url']}&amp;id_file_delete={$l['id_file']}');"><img src="/templates/global_img/delete.gif" alt="" /></a>
		      </div>
		      <div class="clear"></div>
		    </form>
		  </li>
		{/foreach}
	      </ul>

	      <div id="node_log{$id}"></div>

	      <script type="text/javascript">
		  {if _NETTE_MODE}
		  $( "#ImageList{!$id}" ).sortable({
		      handle: 'span',
		      update: function(event, ui) {
			var list = $(this).sortable('toArray').toString();

			$.get({$parsed_url['url']} + '&ajax_galler_image_order='+ list);
		     }
		  });

		  $('.imageForm').submit( function(e){
			e.preventDefault();
			$.get({$parsed_url['url']} + '&ajax_save_description=1&'+ $(this).serialize());
			});
		  {else}

			window.addEvent('domready', function() {
			  new Sortables($('ImageList'+{$id}), {
			    cloneOpacity:.1,
			    handle: 'span',
			    onComplete: function() {
				var req = new Request.HTML({
				   method: 'get',
				   url: {$parsed_url['url']} + '&ajax_galler_image_order='+this.serialize(function(el) { return el.id; }),
				   update: $('node_log' + {$id})
			       }).send();
			    }
			  });

			  $$('.imageForm').addEvent('submit', function(e){
				e.stop();

				var req = new Request.HTML({
				   method: 'get',
				   url: {$parsed_url['url']} + '&ajax_save_description=1&'+ this.toQueryString()
			       }).send();
				});

			});

		{/if}


	    </script>