{snippet defaultcart}


<div class="detail-kosika">
	<form action="{plink cart:calculate!}" method="post" id="cartForm" class="ajax">
		{if isset($products) AND count($products) > 0}
			<div class="table">


			  <div class="tr">
				<div class="th img"></div>
				<div class="th name">Názov</div>
				
				<div class="th code">Kód</div>
				<div class="th price">Cena/MJ</div>
				<div class="th count">Počet</div>
				<div class="th price">Cena spolu</div>
				{if $controls}<div class="th icon">Zmaž</div>{/if}
			  </div>


			{foreach $products as $p}
			  <div class="tr {if $iterator->isOdd()}neparne{/if}">
				  
				<div class="td img">					
					<a rel="prettyPhoto" href="{$p['first_file']|img:600:480:1}"><img src="{$p['first_file']|img:40:40:5}" alt="{$p['name']}" /></a>				
				</div>
				<div class="td name">					
					{$p['name']}					
				</div>
				<div class="td code">{$p['code']}</div>
				<div class="td price">{$p['price_array']['price']|money:$presenter->id_lang}</div>
				<div class="td count">{if $controls}<input maxlength="3" type="text" value="{$p['count']}" name="product_count_{$p['id_product_param']}" class="detail-kosika-pocet-kusov" />{else}{$p['count']}{/if}</div>
				<div class="td price">{$p['sum_price']|money:$presenter->id_lang}</div>
				{if $controls}<div class="td icon"><div class="ico-kos"><a href="{plink cart:unsetProduct! $p['id_product_param']}" class="ajax" title="zmazat"></a></div></div>{/if}
			  </div>
			{/foreach}

			
			<div class="delivery tr neparne">
				<div class="td img"></div>
				<div class="td name">Cena dopravy</div>
				<div class="td code"></div>
				<div class="td price"></div>
				<div class="td count"></div>
				<div class="td price">{$delivery_price['price']|money:$presenter->id_lang}</div>
				{if $controls}<div class="td icon"></div>{/if}
			</div>
			

			</div><!-- end table -->
		


			{if $controls}
				<div class="c-btn-calculate">
					<input  style="float:right;" type="submit" name="btn_recalculate" value="{!_'Prepočítať'}"/>
				</div>
			{/if}
			<div class="suma-price">
				
			{*{if $discount}
			<p>Zľava: {$discount|money:$presenter->id_lang}</p>
			{/if}*}
			<p>Suma bez DPH: {$total_sum|money:$presenter->id_lang}</p>

			<p>DPH 20%: {$total_sum_with_tax - $total_sum|money:$presenter->id_lang}</p>
			<p class="price-dph"><strong>Celkom s DPH: {$total_sum_with_tax|money:$presenter->id_lang}</strong></p>

			</div>
		{else}

			{*<div style="padding-bottom: 20px; color: red;">{!_('Košík je prázdny.')}</div>*}
			{control msg 'Košík je prázdny.','','error'}

		{/if}
	</form>


	</div><!-- detail kosika -->

<script type="text/javascript">

</script>

{/snippet}


