 {*<form action="" method="post" style="padding:0px 10px;">
      Text:<br />
      <textarea name="text" style="width:99%;height: 130px;" rows="1" cols="10">{$l['text']}</textarea><br />

	 
      <input style="margin-top:5px;" type="submit" name="saveHome" value="Ulož" />
      <input type="hidden" name="id_node" value="{$l['id_node']}" />
    </form>*}

<div class="module-content">
 <form action="" method="post">
      Titulok:<br />
      <input type="text" class="text" name="text" value="{$l['text']}" /> 
      <input class="submit" type="submit" name="saveHome" value="Ulož" />
      <input type="hidden" name="id_node" value="{$l['id_node']}" />
    </form>
<div class="clear"></div>


{$showPromo}
	</div>