@{block content}

<div class="submenu">
    <a href="{link Eshop:default}">spať</a>
    <h2>{!_('Editácia kategórie')} </h2>
    <div class="clear"></div>
</div>

<div>
    <div class="category-form-container">
	{control editCategoryForm}
    </div>

    <div class="files-container">
	<h1>Súborový manažér</h1>
	{$filesModule->render()}
    </div>
    
    <div class="clear"></div>
</div>

<script type="text/javascript">
    $("tr:nth-child(odd)").addClass("odd");
    $('table').highlight();
</script>

