<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="sk" lang="sk">
    <head>
    <title n:ifset="$page['title']">{$page['title']}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="sk" />
	<meta http-equiv="content-style-type" content="text/css" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta name="googlebot" content="index,follow,snippet,noarchive"/>
	<meta name="robots" content="all" />
	
	<meta n:ifset="$page['keywords']" name="classification" content="{$page['keywords']}"/>
	
	<meta name="resource-type" content="document" />
	<meta name="distribution" content="global" />
	<meta name="copyright" content="2008 - {?echo date("Y")} {ifset $var}{$var['autor']}{/ifset}" />
	<meta n:ifset="$page['keywords']" name="keywords" content="{$page['keywords']}" />
	<meta n:ifset="$page['description']" name="description" content="{$page['description']}" />
	{if $css}
		{foreach $css as $c}
			<link rel="stylesheet" href="{$c}" type="text/css" />
		{/foreach}
	{/if}
	
	{if $scripts}
		{foreach $scripts as $script}
			<script type="text/javascript" src="{$script}"></script>
		{/foreach}
	{/if}
	
	<script type="text/javascript">
		{if $textScripts}
			{foreach $textScripts as $script}
					{!$script}
			{/foreach}
		{/if}
	</script>
	
</head>
<body>
