{block #content}

{include '../default-top.latte' 
	breadcrumb=>array( array('name'=>_('Obnova hesla')) ), 
	name=>_('Zabudli ste heslo?')
}


	<div class="content">
	<p>
	<strong>Vložte prosím Vaše používateľské meno(e-mailovú adresu) a kliknite na "Odoslať heslo".</strong><br />
	Onedlho dostanete nové heslo. Použite toto nové heslo na prihlásenie na stránky.
	</p>
	<div class="profil-form-container">
		<style>#frm-lostPasswordForm table th{ width:140px;}</style>
	{control lostPasswordForm}
		</div>

	</div>

