Dobrý deň {$values['name']},<br /><br />

ďakujeme za Vašu registráciu na eshope Donatio - propagacnepredmety.sk. Odteraz môžete v našom internetovom obchode kedykoľvek pohodlne nakupovať po prihlásení sa svojimi prihlasovacími údajmi, ktoré sú:<br /><br />

E-mailová adresa: {$values['login']}<br />
Vaše heslo: (ako ste si zvolili pri registrácii)<br /><br />

Najnovšie informácie o Vašich objednávkach, ako aj všetky ostatné informácie nájdete po prihlásení v sekcii vo Vašom profile.<br /><br />

Ešte raz Vám ďakujeme za dôveru a želáme úspešný vstup do nakupovania na internete na Donatio - propagacnepredmety.sk!<br /><br />


{? echo $presenter->context->params['footer_for_emails']}