{contentType application/xml; charset=utf-8}
<{? echo'?'}xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	  {foreach $sitemap as $s}
      <url>
      <loc>http://{? echo $_SERVER['HTTP_HOST']}{plink :Front:Eshop:default id=>$s['id_category']}</loc>
      <lastmod>{? echo date('Y-m-d');}</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.8</priority>
      </url>
      {/foreach}
</urlset>