{block content}

	<div class="submenu">
		
		<a href="{plink order:}">spať</a>

		 <h2>Náhľad objednávky </h2>
		<div class="clear"></div>
	</div>
{*
<a style="float: right;padding-right:20px;padding-top: 20px; text-decoration:none;" href="{plink generateExcel id_order=>$presenter->param['id']}">Generovať faktúru <img style="vertical-align: sub;" src="/images/excel_icon.png" alt="Generovat excel" /></a>
*}
<div class="status-form">{control statusForm}</div>

<div style="padding:20px">
{include '/'.APP_DIR.'/FrontModule/templates/Profil/order.phtml' show_breadcrumb=>false}

	</div>