<div class="submenu-clankovanie">
<div class="submenu-clankovanie-pic"><img src="{$image['thumbs']}" alt="" title="" /></div>
<div class="submenu-clankovanie-nadpis"><a href="{$product['url']}">{$product['title']}</a></div>
<div class="submenu-clankovanie-dalej"><a href="{$product['url']}">detail produktu <img src="/images/li.gif" /></a></div>

		</div><!-- submenu clankovanie -->


{*
<div class="clanok">
	<a href="{$product['url']}">

<h3>{$product['title']}</h3>

<div class="clanok-pic"><img src="{$image['thumbs']}" alt="" title="" /></div>

<span>
{$product['text']|striptags|truncate:90}
	</span>
		</a>
			</div>
			
		*}