{**
 * GUI for Acl layout template.
 *
 * @copyright  Copyright (c) 2010 Tomas Marcanik
 * @package    GUI for Acl
 *
 * @param string   $basePath web base path
 * @param string   $user users methods (if authenticated)
 * @param string   $identity users identity (if authenticated)
 * @param array    $flashes  flash messages
 * @param string   $current current presenter
 *}
{control header}
<body>
    <div id="menu">
        <ul>
            <li{if $current=='Acl:Users'} class="hover"{/if}><a href="{plink //Users:default}">Users</a></li>
            <li{if $current=='Acl:Permission'} class="hover"{/if}><a href="{plink //Permission:}">Permission</a></li>
            <li{if $current=='Acl:Roles'} class="hover"{/if}><a href="{plink //Roles:}">Roles</a></li>
            <li{if $current=='Acl:Resources'} class="hover"{/if}><a href="{plink //Resources:}">Resources</a></li>
            <li{if $current=='Acl:Privileges'} class="hover last"{/if}><a href="{plink //Privileges:}">Privileges</a></li>
            {if $user->isLoggedIn()}
            <li class="last"><a href="{plink :Admin:Login:out}">Logout [{$identity->name}]</a></li>
            {else}
            <li class="last"><a href="{plink :Admin:Login:}">Login</a></li>
            {/if}
        </ul>
    </div>
    <div id="content">
        {if count($flashes)}
        <ul class="error">
            {foreach $flashes as $flash}<li{ifset $flash->type} class="{$flash->type}"{/ifset}>{$flash->message}</li>{/foreach}
        </ul>
        {/if}
	{include #content}
        
    </div>
   
<script type="text/javascript">
$("ul.border_parent").parent().css("border-left", "1px solid grey");
</script>
</body>
</html>