{block content}

<script type="text/javascript">
	tinyMCE.init({
		// General options
		mode : "textareas",
		theme : "advanced",
		plugins : "spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,filemanager",

		// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,undo,redo,forecolor,bullist,link,unlink,image,media,cleanup,removeformat",
		theme_advanced_buttons2 : "formatselect,justifyleft,justifycenter,justifyright,justifyfull,code",
		theme_advanced_buttons3 : "",


		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",

		theme_advanced_resizing : false,


		language : "sk",
		relative_urls : false,
		entity_encoding : "raw",
		remove_script_host : false,
        convert_urls : false,
		cleanup : true


	});
</script>


<div class="newsletter">
	

	{*<div class="choose-template">
		<ul>
			<li>
				<div style="text-align:center;">
					<img src="/images-system/newsletter/templates/template-1.png" alt="" /><br />
					<input type="radio" name="template[]" checked="checked"/>
				</div>
			</li>
		</ul>
		<div class="clear"></div>
	</div>*}
	<h1>Newsletter</h1>
	<div style="padding: 10px 0;">
	<h3>Pridanie emailov <small>( pre vloženie viacej emailových adresie odelte emaili čiarkou)</small></h3>
	{$addform->render('begin')}
	{!$addform['emails']->label}
	{!$addform['emails']->control}

	{!$addform['btn']->control}
	{$addform->render('end')}

	</div>
	
	<h1>Správa na odoslanie</h1>
	<div style="padding: 10px 0;">
		{$form->render('begin')}
		{$form->render('errors')}
		<div class="subject-holder">
			{!$form['subject']->label}
			{!$form['subject']->control}
		</div>
		{!$form['text']->control}
		
		
		
		<div style="padding:10px;float:left;">
		{!$form['my_email']->label}
		{!$form['my_email']->control}
		{!$form['btn_send_to_me']->control}
		</div>

		<div class="send-input-holder" style="width:200px;">
			{!$form['btn_send_emails']->control}<br />
			<small>Newsletter sa odošle na všetky emaili, ktoré sú označené. Ak neoznačíte ani jeden email, odošle sa newsletter na všetky emaili.</small>
		</div>
		<div class="clear"></div>
		
		
		{$form->render('end')}
	</div>

	{snippet checkedEmails}
		
		<div class="checked-email-holder">
			<fieldset>
				<strong>Označené  ({? echo count($checked_emails)}) </strong><br />
			{foreach $checked_emails as $e} {$e['email']}{if !$iterator->isLast()},{/if}{/foreach}
			</fieldset>
		</div>
	{/snippet}
	
	
	
	
	
	
	{control newsletterTabella}
	
	<script>
		$('.checked_emails').live('click', function() {
			
			if( $(this).is(':checked')){
				$.get({link checkedEmail! 1} + '&id_newsletter_emails=' + $(this).val());
			}else{
				$.get({link checkedEmail! 0} + '&id_newsletter_emails=' + $(this).val());
			}
		});
	</script>
</div>